---
# database
- name: Create gitbucket database
  mysql_db: name={{ gitbucket_db_name }} state=present

- name: Create gitbucket user and 'WITH GRANT OPTION'
  mysql_user:
    name: "{{ gitbucket_db_user }}"
    password: "{{ gitbucket_db_password }}"
    priv: "{{ gitbucket_db_name }}.*:ALL,GRANT"
    host: "{{ gitbucket_db_host }}"
    state: present

# configure
- name: Create gitbucket home directory
  file: path=/home/tomcat/.gitbucket state=directory owner=tomcat group=tomcat

- name: Copy database conf file in place.
  template: src=database.conf.j2 dest=/home/tomcat/.gitbucket/database.conf owner=tomcat group=tomcat
  notify:
    - restart tomcat

# install
- name: Download gitbucket.war
  get_url: url={{ gitbucket_war_download_url }} dest={{ gitbucket_war_file_path }} owner=tomcat group=tomcat
  notify:
    - restart tomcat

# backup
- name: Create backup group.
  group: name=backup

- name: Create backup user.
  user: name=backup group=backup shell=/sbin/nologin

- name: Create backup directory.
  file: path=/home/backup/gitbucket state=directory owner=backup group=backup
