---
- include: docker-{{ ansible_os_family }}.yml
  static: no
  when: ansible_connection == 'docker'

- name: Download gitbucket.war
  get_url:
    url: https://github.com/gitbucket/gitbucket/releases/download/{{ gitbucket_version }}/gitbucket.war
    dest: /opt/gitbucket.war